### ISSUE TITLE
无法加载内置的schedule插件

### ISSUE THREAD

**Issue by a147022899** [cczu-osa/amadeus#34]
`[2020-09-04 18:08:20,221 nonebot] ERROR: Failed to import "aki.plugins.schedule", error: cannot import name 'parse_command' from 'nonebot.command' (/root/anaconda3/lib/python3.8/site-packages/nonebot/command/__init__.py)
[2020-09-04 18:08:20,221 nonebot] ERROR: cannot import name 'parse_command' from 'nonebot.command' (/root/anaconda3/lib/python3.8/site-packages/nonebot/command/__init__.py)
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/nonebot/plugin.py", line 252, in load_plugin
    module = importlib.import_module(module_path)
  File "/root/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/Robot-Test/aki/aki/plugins/schedule/__init__.py", line 7, in <module>
    from nonebot.command import parse_command
ImportError: cannot import name 'parse_command' from 'nonebot.command' (/root/anaconda3/lib/python3.8/site-packages/nonebot/command/__init__.py)`
每次Aki启动时都是这种样子，代码是git clone的，这使得计划任务功能无法使用。请好心的大佬为我们提供一些修复思路，谢谢。也许是notebot py包的升级，使得该插件里面的函数被替代了。我的python水平不高，并不清楚notebot的api用法。

**Comment by tianruiMM** [comment]
command_manager = CommandManager()
cmd, current_arg = command_manager.parse_command(session.bot, cmd_str)

改成👆试试

**Comment by stdrc** [comment]
很好奇这个项目还有人在用吗，已经弃坑好久了😂

**Comment by sdy623** [comment]
我在使用啊，忽略这个错误就行了
